sudo: required
os:
- linux
- osx
dist: trusty
osx_image: xcode8
language: node_js
node_js:
- '4'
- '6'
- '8'
- '9'
matrix:
  allow_failures:
  - node_js: '9'
cache:
- apt: true
- directories:
  - "node_modules"
  - "$HOME/.electron"
before_install: ci/before_install.sh
install:
- npm install
- npm run bu
before_script:
after_success: npm run codecov
branches:
addons:
    apt:
      packages:
        - xvfb
  install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
env:
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"
