sudo: required
os:
- linux
- osx
dist: trusty
osx_image: xcode9.2
language: node_js
node_js:
- 'node'
matrix:
  allow_failures:
cache:
- apt: true
- directories:
  - "node_modules"
  - "$HOME/.electron"
before_install:
- bash test/ci/before_install.sh
install:
- export DISPLAY=':99.0'
- xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm install -g codecov
- npm install
- npm update
script:
- npm run build
- codecov
before_script:
after_success: npm run codecov
branches:
addons:
  apt:
    packages:
    - xvfb
env:
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"
